/** @type {import('stylelint').Config} */
export default {
  extends: [
    'stylelint-config-standard',
    'stylelint-config-recommended'
  ],
  plugins: [
    'stylelint-order'
  ],
  rules: {
    'order/properties-order': [
      'position',
      'top',
      'right',
      'bottom',
      'left',
      'z-index',
      'display',
      'flex',
      'flex-direction',
      'flex-wrap',
      'justify-content',
      'align-items',
      'align-content',
      'grid',
      'grid-template',
      'grid-template-columns',
      'grid-template-rows',
      'grid-template-areas',
      'grid-gap',
      'order',
      'width',
      'min-width',
      'max-width',
      'height',
      'min-height',
      'max-height',
      'padding',
      'padding-top',
      'padding-right',
      'padding-bottom',
      'padding-left',
      'margin',
      'margin-top',
      'margin-right',
      'margin-bottom',
      'margin-left',
      'border',
      'border-top',
      'border-right',
      'border-bottom',
      'border-left',
      'border-radius',
      'background',
      'background-color',
      'background-image',
      'background-repeat',
      'background-position',
      'background-size',
      'color',
      'font',
      'font-family',
      'font-size',
      'font-weight',
      'font-style',
      'text-align',
      'text-decoration',
      'text-transform',
      'letter-spacing',
      'line-height',
      'overflow',
      'opacity',
      'visibility',
      'box-shadow',
      'transform',
      'transition',
      'animation'
    ],
    'indentation': 2,
    'string-quotes': 'double',
    'color-hex-case': 'lower',
    'color-hex-length': 'short',
    'unit-case': 'lower',
    'property-case': 'lower',
    'selector-class-pattern': '^[a-z][a-zA-Z0-9_-]*$',
    'selector-id-pattern': '^[a-z][a-zA-Z0-9_-]*$',
    'max-nesting-depth': 3,
    'selector-max-compound-selectors': 3,
    'declaration-block-no-duplicate-properties': true,
    'no-descending-specificity': null,
    'at-rule-no-unknown': [
      true,
      {
        ignoreAtRules: [
          'extends',
          'ignores',
          'mixin',
          'include',
          'function',
          'return',
          'each',
          'for',
          'if',
          'else',
          'warn',
          'error'
        ]
      }
    ]
  },
  ignoreFiles: [
    'assets/css/vendor/**/*.css',
    'node_modules/**/*.css',
    'vendor/**/*.css',
    '**/*.min.css'
  ]
};